name: CMD

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: docker version
        run: docker buildx version
      - name: os release
        run: cat /etc/os-release